import ExcelJS from 'exceljs';
import path from 'node:path';
import fs from 'node:fs';
import type { AiTestSummary } from './geminiReportWriter';

export type TestStatus = 'passed' | 'failed' | 'timedOut' | 'skipped';

export interface TestResult {
  testId: string;
  title: string;
  status: TestStatus;
  durationMs?: number;
  error?: string;
  expectedEvidence?: string;
  actualEvidence?: string;
}

function styleHeader(sheet: ExcelJS.Worksheet): void {
  const header = sheet.getRow(1);
  header.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  header.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF1F4E78' },
  };
  header.alignment = { vertical: 'middle', wrapText: true };
  header.height = 28;
  sheet.views = [{ state: 'frozen', ySplit: 1 }];
  sheet.columns.forEach(column => {
    column.width = Math.max(column.width ?? 12, 18);
  });
}

function applyBodyFormatting(sheet: ExcelJS.Worksheet): void {
  sheet.eachRow((row, rowNumber) => {
    if (rowNumber > 1) {
      row.alignment = { vertical: 'top', wrapText: true };
    }
  });
}

function statusLabel(status: TestResult['status']): string {
  if (status === 'timedOut') return 'Timed Out';
  return status.charAt(0).toUpperCase() + status.slice(1);
}

export async function generateExcelReport(
  testResults: TestResult[],
  aiReport: AiTestSummary | null,
  outputPath = path.resolve(
    process.cwd(),
    'tests',
    'bug-reports',
    `Automation_Bug_Report_${Date.now()}.xlsx`,
  ),
  aiError?: string,
): Promise<string> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Playwright QA Automation';
  workbook.created = new Date();

  const passed = testResults.filter(test => test.status === 'passed');
  const failed = testResults.filter(test => test.status === 'failed');
  const timedOut = testResults.filter(test => test.status === 'timedOut');
  const skipped = testResults.filter(test => test.status === 'skipped');

  // Sheet 1: Test Summary. Counts always come from Playwright, never Gemini.
  const summary = workbook.addWorksheet('Test Summary');
  summary.addRows([
    ['Metric', 'Value'],
    ['Total Tests', testResults.length],
    ['Passed', passed.length],
    ['Failed', failed.length],
    ['Timed Out', timedOut.length],
    ['Skipped', skipped.length],
    ['AI Report Status', aiReport ? 'Generated by Gemini' : 'Gemini generation failed'],
    ['AI Overall Summary', aiReport?.overallSummary ?? `AI summary unavailable. ${aiError ?? ''}`],
  ]);
  styleHeader(summary);
  applyBodyFormatting(summary);
  summary.getColumn(1).width = 28;
  summary.getColumn(2).width = 100;

  // Sheet 2: Passed Tests.
  const passedSheet = workbook.addWorksheet('Passed Tests');
  passedSheet.addRow(['Test ID', 'Test Name', 'Status', 'Duration (ms)', 'Gemini Summary']);
  const passMap = new Map((aiReport?.passedSummaries ?? []).map(item => [item.testId, item.summary]));
  for (const test of passed) {
    passedSheet.addRow([
      test.testId,
      test.title,
      statusLabel(test.status),
      test.durationMs ?? '',
      passMap.get(test.testId) ?? 'Gemini description unavailable',
    ]);
  }
  styleHeader(passedSheet);
  applyBodyFormatting(passedSheet);

  // Sheet 3: Failed Tests includes failed and timed-out tests.
  const failedSheet = workbook.addWorksheet('Failed Tests');
  failedSheet.addRow([
    'Test ID', 'Test Name', 'Status', 'Duration (ms)', 'Failure Summary',
    'Error Details', 'Expected Result', 'Actual Result',
  ]);
  const failureMap = new Map(
    (aiReport?.failedSummaries ?? []).map(item => [item.testId, item]),
  );
  for (const test of [...failed, ...timedOut]) {
    const ai = failureMap.get(test.testId);
    failedSheet.addRow([
      test.testId,
      test.title,
      statusLabel(test.status),
      test.durationMs ?? '',
      ai?.failureSummary ?? 'Gemini description unavailable',
      test.error ?? '',
      ai?.expectedResult ?? 'Not available',
      ai?.actualResult ?? 'Not available',
    ]);
  }
  styleHeader(failedSheet);
  applyBodyFormatting(failedSheet);

  // Sheet 4: Bug Report. Only failed/timed-out records with Gemini output.
  const bugSheet = workbook.addWorksheet('Bug Report');
  bugSheet.addRow([
    'Bug ID', 'Test ID', 'Bug Title', 'Severity', 'Priority',
    'Steps to Reproduce', 'Expected Result', 'Actual Result', 'Status',
  ]);

  let bugNumber = 1;
  for (const test of [...failed, ...timedOut]) {
    const ai = failureMap.get(test.testId);
    if (!ai) continue;

    bugSheet.addRow([
      `BUG-${String(bugNumber++).padStart(3, '0')}`,
      test.testId,
      ai.bugTitle,
      ai.severity || 'Unassigned',
      ai.priority || 'Unassigned',
      ai.stepsToReproduce.join('\n'),
      ai.expectedResult,
      ai.actualResult,
      test.status === 'timedOut' ? 'Needs Review - Timed Out' : 'Open - Reported',
    ]);
  }
  styleHeader(bugSheet);
  applyBodyFormatting(bugSheet);

  if (!aiReport) {
    const note = workbook.addWorksheet('AI Generation Status');
    note.addRows([
      ['Status', 'Details'],
      ['Failed', aiError ?? 'Gemini did not return a report.'],
      ['Note', 'Playwright test results are retained. AI descriptions were not generated.'],
    ]);
    styleHeader(note);
    applyBodyFormatting(note);
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  await workbook.xlsx.writeFile(outputPath);
  return outputPath;
}
